/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fadhilah;


public class menuminuman extends javax.swing.JFrame {

   
    public menuminuman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbkopimilo = new javax.swing.JCheckBox();
        cakopisusulight = new javax.swing.JCheckBox();
        cbkopimatcha = new javax.swing.JCheckBox();
        cbkopiregal = new javax.swing.JCheckBox();
        cbkopiyogurt = new javax.swing.JCheckBox();
        cbmatchamacchiato = new javax.swing.JCheckBox();
        cbblacksugarmilktea = new javax.swing.JCheckBox();
        cbavocadochoco = new javax.swing.JCheckBox();
        cbmanggotea = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtjumlah2 = new javax.swing.JTextField();
        txtjumlah3 = new javax.swing.JTextField();
        txtjumlah4 = new javax.swing.JTextField();
        txtjumlah5 = new javax.swing.JTextField();
        txtjumlah6 = new javax.swing.JTextField();
        txtjumlah7 = new javax.swing.JTextField();
        txtjumlah8 = new javax.swing.JTextField();
        txtjumlah9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txapesan = new javax.swing.JTextArea();
        btnorder = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        txtjumlah111 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Menu Minuman :");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Harga :");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Jumlah :");

        cbkopimilo.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        cbkopimilo.setForeground(new java.awt.Color(102, 102, 102));
        cbkopimilo.setText("kopi Milo");
        cbkopimilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkopimiloActionPerformed(evt);
            }
        });

        cakopisusulight.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cakopisusulight.setForeground(new java.awt.Color(102, 102, 102));
        cakopisusulight.setText("kopi Susu light");
        cakopisusulight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cakopisusulightActionPerformed(evt);
            }
        });

        cbkopimatcha.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        cbkopimatcha.setForeground(new java.awt.Color(102, 102, 102));
        cbkopimatcha.setText("Kopi Matcha");
        cbkopimatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkopimatchaActionPerformed(evt);
            }
        });

        cbkopiregal.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        cbkopiregal.setForeground(new java.awt.Color(102, 102, 102));
        cbkopiregal.setText("Kopi Regal");

        cbkopiyogurt.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        cbkopiyogurt.setForeground(new java.awt.Color(102, 102, 102));
        cbkopiyogurt.setText("Kopi Yogurt");

        cbmatchamacchiato.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        cbmatchamacchiato.setForeground(new java.awt.Color(102, 102, 102));
        cbmatchamacchiato.setText("Matcha Macchiato");
        cbmatchamacchiato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmatchamacchiatoActionPerformed(evt);
            }
        });

        cbblacksugarmilktea.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        cbblacksugarmilktea.setForeground(new java.awt.Color(102, 102, 102));
        cbblacksugarmilktea.setText("Blacksugar Milk Tea");
        cbblacksugarmilktea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbblacksugarmilkteaActionPerformed(evt);
            }
        });

        cbavocadochoco.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        cbavocadochoco.setForeground(new java.awt.Color(102, 102, 102));
        cbavocadochoco.setText("Avocado Choco");

        cbmanggotea.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        cbmanggotea.setForeground(new java.awt.Color(102, 102, 102));
        cbmanggotea.setText("Manggo Tea");
        cbmanggotea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmanggoteaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Rp. 12.000");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Rp. 15.000");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Rp. 15.000");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Rp. 18.000");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Rp. 18.000");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Rp. 16.000");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Rp. 20.000");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Rp. 22.000");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Rp. 15.000");

        txtjumlah2.setBackground(new java.awt.Color(204, 204, 204));

        txtjumlah3.setBackground(new java.awt.Color(204, 204, 204));

        txtjumlah4.setBackground(new java.awt.Color(204, 204, 204));

        txtjumlah5.setBackground(new java.awt.Color(204, 204, 204));

        txtjumlah6.setBackground(new java.awt.Color(204, 204, 204));

        txtjumlah7.setBackground(new java.awt.Color(204, 204, 204));

        txtjumlah8.setBackground(new java.awt.Color(204, 204, 204));
        txtjumlah8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah8ActionPerformed(evt);
            }
        });

        txtjumlah9.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setBackground(new java.awt.Color(255, 153, 153));
        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("#KEDAI KITA#");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Menu yang di order: ");

        txapesan.setBackground(new java.awt.Color(204, 204, 204));
        txapesan.setColumns(20);
        txapesan.setRows(5);
        jScrollPane1.setViewportView(txapesan);

        btnorder.setBackground(new java.awt.Color(153, 153, 153));
        btnorder.setText("Order");
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(153, 153, 153));
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        txtjumlah111.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbkopimilo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbkopimatcha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbkopiregal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbkopiyogurt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbmatchamacchiato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbblacksugarmilktea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbavocadochoco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbmanggotea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cakopisusulight)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel4)))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtjumlah111)
                        .addGap(320, 320, 320))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtjumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjumlah9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1)
                                        .addGap(16, 16, 16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnorder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(btnreset)
                                .addGap(43, 43, 43))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel2)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cakopisusulight)
                    .addComponent(jLabel4)
                    .addComponent(txtjumlah111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbkopimilo)
                    .addComponent(jLabel5)
                    .addComponent(txtjumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbkopimatcha)
                    .addComponent(jLabel6)
                    .addComponent(txtjumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbkopiregal)
                            .addComponent(jLabel8))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbkopiyogurt)
                            .addComponent(jLabel9)
                            .addComponent(txtjumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addComponent(txtjumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbmatchamacchiato)
                                .addComponent(jLabel10))
                            .addComponent(txtjumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(txtjumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbblacksugarmilktea)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbavocadochoco)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtjumlah8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnorder)
                                    .addComponent(btnreset)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbmanggotea)
                                    .addComponent(jLabel12)
                                    .addComponent(txtjumlah9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbmanggoteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmanggoteaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmanggoteaActionPerformed

    private void cbmatchamacchiatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmatchamacchiatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmatchamacchiatoActionPerformed

    private void cbkopimatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkopimatchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkopimatchaActionPerformed

    private void cakopisusulightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cakopisusulightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cakopisusulightActionPerformed

    private void cbkopimiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkopimiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkopimiloActionPerformed

    private void cbblacksugarmilkteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbblacksugarmilkteaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbblacksugarmilkteaActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        // TODO add your handling code here:
        String tampil  ;
        tampil = "";
        int bayar = 0;
        if(cakopisusulight.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah111.getText());
            int total;
            total=jumlah*12000;
            bayar=bayar+total;
            tampil+=cakopisusulight.getText()+" Rp.12000"+" x "+ jumlah+" = "+total+"\n";
        } if(cbkopimilo.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah2.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil+=cbkopimilo.getText()+" Rp.15000"+" x "+ jumlah+" = "+total+"\n";
        }if(cbkopimatcha.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah3.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil+=cbkopimatcha.getText()+" Rp.15000"+" x "+ jumlah+" = "+total+"\n";
        }if(cbkopiregal.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah4.getText());
            int total;
            total=jumlah*18000;
            bayar=bayar+total;
            tampil+=cbkopiregal.getText()+" Rp.18000"+" x "+ jumlah+" = "+total+"\n";
        }if(cbkopiyogurt.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah5.getText());
            int total;
            total=jumlah*18000;
            bayar=bayar+total;
            tampil+=cbkopiyogurt.getText()+" Rp.18000"+" x "+ jumlah+" = "+total+"\n";
        }if(cbmatchamacchiato.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah6.getText());
            int total;
            total=jumlah*16000;
            bayar=bayar+total;
            tampil+=cbmatchamacchiato.getText()+" Rp.16000"+" x "+ jumlah+" = "+total+"\n";
        }if(cbblacksugarmilktea.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah7.getText());
            int total;
            total=jumlah*20000;
            bayar=bayar+total;
            tampil+=cbblacksugarmilktea.getText()+" Rp.20000"+" x "+ jumlah+" = "+total+"\n";
        }if(cbavocadochoco.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah8.getText());
            int total;
            total=jumlah*22000;
            bayar=bayar+total;
            tampil+=cbavocadochoco.getText()+" Rp.22000"+" x "+ jumlah+" = "+total+"\n";
        }if(cbmanggotea.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah9.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil+=cbmanggotea.getText()+" Rp.15000"+" x "+ jumlah+" = "+total+"\n";
        }
        txapesan.setText(tampil+"---------------------------------------------------"+"\n"+"Total Bayar : "+bayar );
        
    }//GEN-LAST:event_btnorderActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtjumlah111.setText("");
        txtjumlah2.setText("");
        txtjumlah3.setText("");
        txtjumlah4.setText("");
        txtjumlah5.setText("");
        txtjumlah6.setText("");
        txtjumlah7.setText("");
        txtjumlah8.setText("");
        txtjumlah9.setText("");
        txapesan.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    private void txtjumlah8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah8ActionPerformed

    /**
     * @param args the command line arguments1
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuminuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnorder;
    private javax.swing.JButton btnreset;
    private javax.swing.JCheckBox cakopisusulight;
    private javax.swing.JCheckBox cbavocadochoco;
    private javax.swing.JCheckBox cbblacksugarmilktea;
    private javax.swing.JCheckBox cbkopimatcha;
    private javax.swing.JCheckBox cbkopimilo;
    private javax.swing.JCheckBox cbkopiregal;
    private javax.swing.JCheckBox cbkopiyogurt;
    private javax.swing.JCheckBox cbmanggotea;
    private javax.swing.JCheckBox cbmatchamacchiato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextArea txapesan;
    private javax.swing.JTextField txtjumlah111;
    private javax.swing.JTextField txtjumlah2;
    private javax.swing.JTextField txtjumlah3;
    private javax.swing.JTextField txtjumlah4;
    private javax.swing.JTextField txtjumlah5;
    private javax.swing.JTextField txtjumlah6;
    private javax.swing.JTextField txtjumlah7;
    private javax.swing.JTextField txtjumlah8;
    private javax.swing.JTextField txtjumlah9;
    // End of variables declaration//GEN-END:variables
}
